### ISSUE TITLE
Use Typst_jll

### ISSUE THREAD

**Issue by asinghvi17** [emfeltham/Typst.jl#1]
Typst_jll exists, so it would be cool to have this package depend on it so the user doesn't have to install Typst!  You can always set the path by an environment variable or local preference.

**Comment by emfeltham** [comment]
Hi, this sounds like a good idea. I was wondering whether you could provide a link to Typst_jll (I cannot seem to find it via a quick search!).

**Comment by asinghvi17** [comment]
https://github.com/juliabinarywrappers/Typst_jll.jl should have it - the SEO for JLLs is particularly bad.  In general I try to search https://github.com/JuliaPackaging/Yggdrasil/ for packages - that's where they are generated from!

**Comment by jakobjpeters** [comment]
You may also find my [Typstry.jl](https://github.com/jakobjpeters/Typstry.jl) package useful! For example:
- An easy-to-use `TypstCommand` rather than using Typst_jll.jl directly
    - ``` typst`help` ```
- An interface to create Typst formatted strings
    -`typst"\(1//2)" == typst"$1 / 2$"`.

**Comment by emfeltham** [comment]
Hi, yes, I think that Typstry.jl is extremely useful here, especially for writing captions. I have imported and reexported this package, and will integrate it.
